{% set version = "1.7-2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-klar
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/klaR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/klaR/klaR_{{ version }}.tar.gz
  sha256: 8035c3edb8257973184ad5a2109fc7c77c32da913cb9dd0c2f1c373e6fccbd61

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-combinat
    - r-questionr
  run:
    - r-base
    - r-mass
    - r-combinat
    - r-questionr

test:
  commands:
    - $R -e "library('klaR')"           # [not win]
    - "\"%R%\" -e \"library('klaR')\""  # [win]

about:
  home: http://www.statistik.tu-dortmund.de
  license: GPL-2.0-or-later
  summary: Miscellaneous functions for classification and visualization, e.g. regularized discriminant analysis, sknn() kernel-density naive Bayes,  an interface to 'svmlight' and stepclass() wrapper variable selection  for supervised classification, partimat() visualization of classification rules  and shardsplot() of cluster
    results as well as kmodes() clustering for categorical data,  corclust() variable clustering, variable extraction from different variable clustering models  and weight of evidence preprocessing.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
