appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: xdrrx69IEhqGUzkO6zFiPsd9/Q5gD9xSBMHzE5h9+Xc5NBXHZ8zUG4as5tsOKT/n1qeaa8wBDkrD7zMC+h2o14TuLDLN6xlYM5az/F/rk1w+C/G/ocpVu8QKD5wzjC3hD7udXd9/Cgrkvd0K/gsWYMxCBWcDr3+pCpb4VXp3p3waQzX/iTtgm1V9OsgTt5LF4CpDQCI/ViahkpBoWiBqcaAq017Ig5xuU0NaPtSZTlXKs1r6ihkHICAIh27wOXNiOPvgY844PvMBTfAq7vchggI/5hu72Ync0A6KQyuT1/ZIgKuhSjOao/hjRU9xCyomz3n2WAY43eg1rnIsvcdISHoPnkKOsgLjO0J0G10xmwopFVrIiZConwnP5NzpZFzGzeTKZv0ofgksuS8MaJ8mh0wXQBiSf5TyH4WMSo82vMh4N6uwLEK1uHJ3UBNhoTp7VN25fJy+NU4tEbduGIykf7MwMQO9uI72kysp3/uHu4ObSX9v8FMp5mQjFtltKrPZPBJuPrZL+vSHeTKbwbhKdJJJxOhsPCqsJk8X0t4yrdjTd1NU+Cjk+bL2TP2ui5CdKh4xGz3gGpQYnDEbrU4qRv0fOofgLDZnBEjB5aC4SeUPUKw/QpO7xqiH4so7WbN/VmFk+aCIpwJuSl/+byyc3r1GuyVfcwk/HiCY5GCHsSI=}
bot:
  automerge: true
